name: release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  update-dls:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Package Registry and run
        run: |
          echo "${{ secrets.PATOKEN }}" | docker login ghcr.io -u "${{ secrets.GHUSER }}" --password-stdin
          docker pull ghcr.io/ryancbutler/ctxscrapper
          docker run -e ctxuser -e ctxpass -v ${PWD}/data:/data ghcr.io/ryancbutler/ctxscrapper
        env:
          ctxuser: ${{ secrets.CTXUSER }}
          ctxpass: ${{ secrets.CTXPASS }}
      - name: Copy ctx_dls to root
        run: mv ./data/ctx_dls.* ./
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated DL files
          file_pattern: ctx_dls.*
