name: release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  update-dls:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Copy script to data
        run: cp ./ctxScrapper.py ./data/
      - name: Login to GitHub Package Registry and run
        run: |
          echo "${{ secrets.PATOKEN }}" | docker login ghcr.io -u "${{ secrets.GHUSER }}" --password-stdin
          docker pull ghcr.io/ryancbutler/ctxscrapper
          docker run -e ctxuser -e ctxpass -v ${PWD}/data:/data ghcr.io/ryancbutler/ctxscrapper:latest
        env:
          ctxuser: ${{ secrets.CTXUSER }}
          ctxpass: ${{ secrets.CTXPASS }}
      - name: Copy ctx_dls to root
        run: mv ./data/ctx_dls.* ./
      - name: Verify JSON
        run: |
          sudo apt-get update
          sudo apt-get install jq -y

          families=$(jq -M '. |= unique_by(.family)' ctx_dls.json )

          if [ -z "$families" ]; then
              echo "Can't load JSON"
              exit 1
          fi

          cvad=$families|jq -r '.[]|select(.family | startswith("cvad"))'
          if [ -z "$cvad" ]; then
              echo "No cvad family found in json!"
              exit 1
          fi

          adc=$families|jq -r '.[]|select(.family | startswith("pvs"))'
          if [ -z "$pvs" ]; then
              echo "No pvs family found in json!"
              exit 1
          fi

          pvs=$families|jq -r '.[]|select(.family | startswith("adc"))'
          if [ -z "$adc" ]; then
              echo "No adc family found in json!"
              exit 1
          fi
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated DL files
          file_pattern: ctx_dls.*
